export const additionalRequests = [
  {
    location: 'LAMBDA 29 FED 1H_2H BATTERY',
    type: 'Ad Hoc',
    description: 'Custom analysis request for well performance optimization.',
    source: 'WorkQueue',
    role: 'Production Engineer',
    assignedTo: undefined,
    arrivalDate: '03/15/24',
    endDate: '03/22/24',
  },
  {
    location: 'SIGMA 40-28-1H WELL',
    type: 'Down Well',
    description: 'Investigation of downwell conditions and maintenance requirements.',
    source: 'WorkQueue',
    role: 'Production Foreman',
    assignedTo: undefined,
    arrivalDate: '03/15/24',
    endDate: '',
  },
  {
    location: 'PHI 37-36 EAST WELL',
    type: 'Ad Hoc',
    description: 'Pressure anomaly investigation and optimization strategy.',
    source: 'WorkQueue',
    role: 'Production Engineer',
    assignedTo: 'Thompson, Sarah',
    arrivalDate: '03/14/24',
    endDate: '03/21/24',
  },
  {
    location: 'IOTA 46-3H 4H TB FACILITY',
    type: 'Down Well',
    description: 'Emergency maintenance inspection for pump failure.',
    source: 'WorkQueue',
    role: 'Production Assistant Foreman',
    assignedTo: 'Chen, Wei',
    arrivalDate: '03/14/24',
    endDate: '',
  },
  {
    location: 'RHO 21-31 WELL',
    type: 'AL Review',
    description: 'Review of artificial lift system performance and optimization opportunities.',
    source: 'WorkQueue',
    role: 'Production Engineer',
    assignedTo: 'O\'Connor, Sean',
    arrivalDate: '03/14/24',
    endDate: '03/21/24',
  },
  {
    location: 'EAST IOTA FEDERAL COM 22-1H WELL',
    type: 'AL Review',
    description: 'Comprehensive ESP performance evaluation and optimization.',
    source: 'WorkQueue',
    role: 'DSC Production Analyst',
    assignedTo: 'Kim, David',
    arrivalDate: '03/13/24',
    endDate: '03/20/24',
  },
  {
    location: 'NORTH PSI 2 CTB 1',
    type: 'Margin',
    description: 'Analysis of well margin and profitability metrics.',
    source: 'WorkQueue',
    role: 'Production Engineer',
    assignedTo: 'Zhang, Min',
    arrivalDate: '03/13/24',
    endDate: '03/20/24',
  },
  {
    location: 'CHI 17 CTB 1',
    type: 'Margin',
    description: 'Economic analysis of artificial lift conversion project.',
    source: 'WorkQueue',
    role: 'DSC Production Analyst',
    assignedTo: 'Martinez, Ana',
    arrivalDate: '03/13/24',
    endDate: '03/20/24',
  },
  {
    location: 'UPSILON 21 PRODUCTION FACILITY',
    type: 'Allocation',
    description: 'Review and adjustment of production allocation methods.',
    source: 'WorkQueue',
    role: 'Production Engineer',
    assignedTo: 'Santos, Miguel',
    arrivalDate: '03/12/24',
    endDate: '',
  },
  {
    location: 'XI 11 CTB 2',
    type: 'Allocation',
    description: 'Production allocation verification for commingled wells.',
    source: 'WorkQueue',
    role: 'Production Foreman',
    assignedTo: 'Wilson, Thomas',
    arrivalDate: '03/12/24',
    endDate: '',
  },
  {
    location: 'XI 23 CTB 2',
    type: 'Production Fault',
    description: 'Investigation of production system fault and remediation planning.',
    source: 'WorkQueue',
    role: 'Production Assistant Foreman',
    assignedTo: 'Nguyen, Lisa',
    arrivalDate: '03/11/24',
    endDate: '03/18/24',
  },
  {
    location: 'RHO 22-32 WELL',
    type: 'Production Fault',
    description: 'Emergency response to sudden production decline.',
    source: 'WorkQueue',
    role: 'Production Foreman',
    assignedTo: 'Brown, Jessica',
    arrivalDate: '03/11/24',
    endDate: '03/18/24',
  },
  {
    location: 'LAMBDA 31 FED 2H_3H BATTERY',
    type: 'Ad Hoc',
    description: 'Production optimization analysis for multi-well pad.',
    source: 'WorkQueue',
    role: 'DSC Production Analyst',
    assignedTo: 'Anderson, Mark',
    arrivalDate: '03/15/24',
    endDate: '03/22/24',
  },
  {
    location: 'PSI 4 CTB 2',
    type: 'Down Well',
    description: 'Downhole equipment performance review.',
    source: 'WorkQueue',
    role: 'Production Assistant Foreman',
    assignedTo: 'Rodriguez, Carlos',
    arrivalDate: '03/14/24',
    endDate: '',
  },
  {
    location: 'SIGMA 42-28-2H WELL',
    type: 'AL Review',
    description: 'Artificial lift system maintenance schedule review.',
    source: 'WorkQueue',
    role: 'Production Foreman',
    assignedTo: 'Patel, Raj',
    arrivalDate: '03/13/24',
    endDate: '03/20/24',
  }
];