export const engineers = [
  'Unassigned',
  'Patel, Raj',
  'Chen, Wei',
  'Thompson, Sarah',
  'Anderson, James',
  'Kim, David',
  'Garcia, Carlos',
  'Nguyen, Lisa',
  'Smith, Michael',
  'Johnson, Emily',
  'Williams, Robert',
  'Brown, Jessica',
  'Taylor, Daniel',
  'Martinez, Ana',
  'Lee, Jennifer',
  'Wilson, Thomas',
  'Gupta, Priya',
  'O\'Connor, Sean',
  'Zhang, Min',
  'Kowalski, Anna',
  'Santos, Miguel'
];